routes/web.php
<?php
use Illuminate\Support\Facades\Artisan;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
Route::get('register', 'Auth\LoginController@showLoginForm');
Route::get('password/reset', 'Auth\LoginController@showLoginForm')->name('password.request');
Route::get('/admin', 'HomeController@index')->name('admin');

Route::prefix('admin')->group(function () {
    Route::get('/notify:email', function () {
        Artisan::call('notify:email');
        return redirect()->route('admin')->with('status', 'Se enviaron los correo con los registros pior vencer, correctamente.');
    });
    Route::resource('imports', 'ImportController');
    Route::resource('exports', 'ExportController');
    Route::resource('logistics', 'LogisticController');
    Route::resource('clients', 'ClientController');
    Route::resource('users', 'UserController');
    Route::resource('shipper', 'ShipperController');
    Route::resource('consignee', 'ConsigneeController');
    Route::resource('linea', 'LineaController');
    Route::resource('mn', 'MnController');
    Route::resource('pol', 'PolController');
    Route::resource('pais', 'PaisController');
    Route::resource('pod', 'PodController');
    Route::resource('almacen', 'AlmacenController');
    Route::resource('tipo', 'TipoController');
    Route::resource('tamanho', 'TamañoController');
    Route::resource('agentes_carga', 'AgenteCargaController');
    Route::resource('agentes_aduana', 'AgenteAduanaController');
    Route::resource('canal', 'CanalController');
    Route::resource('tipo_import', 'TipoImportController');
    Route::resource('destino', 'DestinoController');
    Route::resource('destino_final', 'DestinoFinalController');
    Route::resource('puerto_transbordo', 'PuertoTransbordoController');
    Route::resource('client', 'ClienteController');
    Route::resource('operation', 'OperationController');
    Route::resource('nave_transbordo', 'NaveTransbordoController');
});


Route::get('/test', function () {

});

app/Cliente.php
<?php

namespace Perumar;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'clientes';
    protected $fillable = [
        'nombre',
        'type'
    ];
}

app/Http/Controllers/ClienteController.php
<?php

namespace Perumar\Http\Controllers;

use Perumar\Cliente;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = Cliente::all();
        return response()->json($clientes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cliente = Cliente::create($request->all());
        return response()->json($cliente);
    }

    /**
     * Display the specified resource.
     *
     * @param  \Perumar\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(Cliente $cliente)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Perumar\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Perumar\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cliente $cliente)
    {
        $cliente->fill($request->all());
        $cliente->save();
        return response()->json($cliente);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Perumar\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cliente $cliente)
    {
        $cliente->delete();
        return response()->json(['message' => 'success']);
    }
}

resources/views/admin/clientes/create.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-sm-12 pb-5">
                <div id="alert" class="alert alert-success alert-dismissible fade d-none" role="alert">
                    <strong>Recurso creado con exito!</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="create-tab" data-toggle="tab" href="#create" role="tab" aria-controls="create" aria-selected="true">
                                    <h4>Agregar Clientes</h4>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="email-tab" data-toggle="tab" href="#email" role="tab" aria-controls="email" aria-selected="false">
                                    <h4>Enviar Email</h4>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="create" role="tabpanel" aria-labelledby="create-tab">
                                {!! Form::open(['id' => 'form_create', 'class'=> '_form']) !!}
                                    <div class="form-row">
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Nro Exportacion') !!}
                                            {!! Form::text('nro_exportacion', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Booking') !!}
                                            {!! Form::text('booking', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Vessel') !!}
                                            {!! Form::text('vessel', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETA callao') !!}
                                            {!! Form::text('eta_callao', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Consignatario') !!}
                                            {!! Form::text('consignatario', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Puerto destino') !!}
                                            {!! Form::text('pod', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Cantidad ctns') !!}
                                            {!! Form::number('cantidad', null, ['class' => 'form-control', 'min' => 0, 'onkeydown'=> 'javascript: return event.keyCode == 69 ? false : true']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('F. Zarpe') !!}
                                            {!! Form::date('fec_zarpe', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Puerto') !!}
                                            {!! Form::text('puerto', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETA') !!}
                                            {!! Form::text('eta', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETD') !!}
                                            {!! Form::text('etd', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Nave transbordo') !!}
                                            {!! Form::text('nave', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Destino final') !!}
                                            {!! Form::text('destino', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4">
                                            {!! Form::label('ETA destino') !!}
                                            {!! Form::text('eta_destino', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4">
                                            {!! Form::label('Perumar N° exportacion') !!}
                                            {!! Form::text('perumar_n_export', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-12">
                                            {!! Form::label('Contenedores') !!}
                                            {!! Form::textarea('contenedores', null, ['class' => 'form-control']) !!}
                                        </div>
                                        {!!form::button('Crear',['id'=>'btn_create','class'=>'btn btn-dark btn-md'])!!}

                                        {!!form::button('Cancelar',['id'=>'cancel','content'=>'Cancelar','class'=>'btn btn-default btn-md'])!!}
                                    </div>
                                {!! Form::close() !!}
                            </div>
                            <div class="tab-pane fade" id="email" role="tabpanel" aria-labelledby="email-tab">
                                {!! Form::open(['id' => 'form_send_email']) !!}
                                    <div class="form-row">
                                        <div class="form-group col-sm-12">
                                            {!! Form::label('Email') !!}
                                            {!! Form::email('email', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-12">
                                            {!! Form::label('Mensaje') !!}
                                            {!! Form::textarea('mensaje', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group form-check">
                                            {!!form::checkbox('send_message', true, null, ['id' => 'send_message'])!!}
                                            {!! Form::label('send_message', 'Quiere enviar un mensaje?', ['class' => 'form-check-label']) !!}
                                        </div>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <div class="modal" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Agregar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {!! Form::open(['method'=>'POST', 'id' => 'form_create_something']) !!}
                        <div class="form-group">
                            {!! Form::label('Nombre') !!}
                            {!! Form::text('nombre', null, ['class' => 'form-control','id'=>'name_']) !!}
                        </div>
                        {!! Form::text('type', 'client', ['class' => 'd-none', 'id'=>'type_']) !!}
                    {!! Form::close() !!}
                    <table class="table table-bordered table-hover table-sm" id="table_some">
                        <thead>
                            <th>ID</th>
                            <th>NOMBRE</th>
                            <th>ACCION</th>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="add_" type="button" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        document.querySelector('#cancel').addEventListener('click', e =>{
            document.location.href = "{{ route('clients.index')}}";
        })
    </script>
@stop

resources/views/admin/clientes/edit.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-sm-12 pb-5">
                <div id="alert" class="alert alert-success alert-dismissible fade d-none" role="alert">
                    <strong>Recurso creado con exito!</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="create-tab" data-toggle="tab" href="#create" role="tab" aria-controls="create" aria-selected="true">
                                    <h4>Agregar Clientes</h4>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="email-tab" data-toggle="tab" href="#email" role="tab" aria-controls="email" aria-selected="false">
                                    <h4>Enviar Email</h4>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                         <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="create" role="tabpanel" aria-labelledby="create-tab">
                                {!! Form::model($client ,['route' => ['clients.update', $client], 'method'=>'PUT','class'=> '_form',  'files'=> true, 'id' => 'form_update']) !!}
                                    <div class="form-row">
                                        {!! Form::text('id', null, ['class' => 'd-none', 'id' => 'id']) !!}
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Nro Exportacion') !!}
                                            {!! Form::text('nro_exportacion', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Booking') !!}
                                            {!! Form::text('booking', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Vessel') !!}
                                            {!! Form::text('vessel', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETA callao') !!}
                                            {!! Form::text('eta_callao', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Consignatario') !!}
                                            {!! Form::text('consignatario', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Puerto destino') !!}
                                            {!! Form::text('pod', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Cantidad ctns') !!}
                                            {!! Form::number('cantidad', null, ['class' => 'form-control', 'min' => 0, 'onkeydown'=> 'javascript: return event.keyCode == 69 ? false : true']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('F. Zarpe') !!}
                                            {!! Form::date('fec_zarpe', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Puerto') !!}
                                            {!! Form::text('puerto', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETA') !!}
                                            {!! Form::text('eta', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('ETD') !!}
                                            {!! Form::text('etd', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Nave transbordo') !!}
                                            {!! Form::text('nave', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4 col-md-3">
                                            {!! Form::label('Destino final') !!}
                                            {!! Form::text('destino', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4">
                                            {!! Form::label('ETA destino') !!}
                                            {!! Form::text('eta_destino', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-4">
                                            {!! Form::label('Perumar N° exportacion') !!}
                                            {!! Form::text('perumar_n_export', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-6">
                                            {!! Form::label('Contenedores') !!}
                                            {!! Form::textarea('contenedores', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-6">
                                            {!! Form::label('Observaciones') !!}
                                            {!! Form::textarea('observaciones', null, ['class' => 'form-control']) !!}
                                        </div>
                                        {!!form::button('Editar',['id'=>'btn_update','class'=>'btn btn-dark btn-md d-flex'])!!}

                                        {!!form::button('Cancelar',['id'=>'cancel','content'=>'Cancelar','class'=>'btn btn-default btn-md'])!!}
                                    </div>
                                {!! Form::close() !!}
                            </div>
                            <div class="tab-pane fade" id="email" role="tabpanel" aria-labelledby="email-tab">
                                {!! Form::open(['id' => 'form_send_email']) !!}
                                    <div class="form-row">
                                        <div class="form-group col-sm-12">
                                            {!! Form::label('Email') !!}
                                            {!! Form::email('email', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group col-sm-12">
                                            {!! Form::label('Mensaje') !!}
                                            {!! Form::textarea('mensaje', null, ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="form-group form-check">
                                            {!!form::checkbox('send_message', true, null, ['id' => 'send_message'])!!}
                                            {!! Form::label('send_message', 'Quiere enviar un mensaje?', ['class' => 'form-check-label']) !!}
                                        </div>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        document.querySelector('#cancel').addEventListener('click', e =>{
            document.location.href = "{{ route('clients.index')}}";
        })
    </script>
@stop

resources/views/admin/clientes/index.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="col-md-12">
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ session('status') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="card">
                <div class="card-header"><h2>Clientes</h2></div>
                <div class="card-body table-responsive">
                    <table class="table table-bordered table-hover table-sm table-responsive">
                        <thead>
                            <th>NRO EXPORTACION</th>
                            <th>BOOKING</th>
                            <th>VESSEL</th>
                            <th>ETA CALLAO</th>
                            <th>CONSIGNATARIO</th>
                            <th>PUERTO DESTINO</th>
                            <th>CANTIDAD CTNS</th>
                            <th>F. ZARPE</th>
                            <th>PUERTO</th>
                            <th>ETA</th>
                            <th>ETD</th>
                            <th>NAVE TRANSBORDO</th>
                            <th>DESTINO FINAL</th>
                            <th>ETA DESTINO</th>
                            <th>PERUMAR N° EXPORTACION</th>
                            <th>CONTENEDORES</th>
                            <th>OBSERVACIONES</th>
                            <th>ACCIÓN</th>
                        </thead>
                        <tbody>
                             @if($clients->count() > 0)
                                @foreach ($clients as $client)
                                    <tr>
                                        <td>{{$client->nro_exportacion}}</td>
                                        <td>{{$client->booking}}</td>
                                        <td>{{$client->vessel}}</td>
                                        <td>{{$client->eta_callao}}</td>
                                        <td>{{$client->consignatario}}</td>
                                        <td>{{$client->pod}}</td>
                                        <td>{{$client->cantidad}}</td>
                                        <td>{{$client->fec_zarpe}}</td>
                                        <td>{{$client->puerto}}</td>
                                        <td>{{$client->eta}}</td>
                                        <td>{{$client->etd}}</td>
                                        <td>{{$client->nave}}</td>
                                        <td>{{$client->destino}}</td>
                                        <td>{{$client->eta_destino}}</td>
                                        <td>{{$client->perumar_n_export}}</td>
                                        <td>{{str_replace('-', '', $client->contenedores)}}</td>
                                        <td>{{str_replace('-', '', $client->observaciones)}}</td>
                                        <td class="d-flex">
                                            <!--<a data-id="{{$client->id}}" class="show-containers btn btn-dark btn-sm" href="javascript:void(0)" data-toggle="tooltip" data-placement="top" title="Mostrar contenedores"><i class="fa fa-th-large" aria-hidden="true"></i></a>-->
                                            <a href="{{route('clients.edit', $client->id)}}" class="btn btn-default btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-edit"></i></a>
                                            <a href="#" class="btn btn-danger btn-sm" onclick="(new actions()).deleteClient({{$client->id}})"  data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="fa fa-trash"></i></a>
                                            {!! Form::open(['route' => ['clients.destroy', $client->id] , 'method' => 'DELETE', 'class' => 'd-none', 'id' => 'delete_client_'.$client->id]) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan = 25 align="center">No tiene clientes</td></tr>
                            @endif
                        </tbody>
                    </table>
                    <div class="d-flex absolute-center">
                        {{$clients->links()}}
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" id="addclient"  name="addclient" class="btn btn-dark" >Agregar Cliente</button>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        function actions(){
            let addBtn = document.querySelector('#addclient');

            addBtn.addEventListener('click', e =>{
                document.location.href = "{{ route('clients.create')}}";
            });
            this.deleteClient= (id) => {
                confirm('¿Seguro que desea eliminar este registro?') ? document.forms['delete_client_'+ id].submit() : null;
            }
        }
        actions();
    </script>
@stop