routes/web.php
<?php
use Illuminate\Support\Facades\Artisan;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
Route::get('register', 'Auth\LoginController@showLoginForm');
Route::get('password/reset', 'Auth\LoginController@showLoginForm')->name('password.request');
Route::get('/admin', 'HomeController@index')->name('admin');

Route::prefix('admin')->group(function () {
    Route::get('/notify:email', function () {
        Artisan::call('notify:email');
        return redirect()->route('admin')->with('status', 'Se enviaron los correo con los registros pior vencer, correctamente.');
    });
    Route::resource('imports', 'ImportController');
    Route::resource('exports', 'ExportController');
    Route::resource('logistics', 'LogisticController');
    Route::resource('clients', 'ClientController');
    Route::resource('users', 'UserController');
    Route::resource('shipper', 'ShipperController');
    Route::resource('consignee', 'ConsigneeController');
    Route::resource('linea', 'LineaController');
    Route::resource('mn', 'MnController');
    Route::resource('pol', 'PolController');
    Route::resource('pais', 'PaisController');
    Route::resource('pod', 'PodController');
    Route::resource('almacen', 'AlmacenController');
    Route::resource('tipo', 'TipoController');
    Route::resource('tamanho', 'TamañoController');
    Route::resource('agentes_carga', 'AgenteCargaController');
    Route::resource('agentes_aduana', 'AgenteAduanaController');
    Route::resource('canal', 'CanalController');
    Route::resource('tipo_import', 'TipoImportController');
    Route::resource('destino', 'DestinoController');
    Route::resource('destino_final', 'DestinoFinalController');
    Route::resource('puerto_transbordo', 'PuertoTransbordoController');
    Route::resource('client', 'ClienteController');
    Route::resource('operation', 'OperationController');
    Route::resource('nave_transbordo', 'NaveTransbordoController');
});


Route::get('/test', function () {

});

resources/views/admin/usuarios/create.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card">
                    <div class="card-header"><h2>Agregar Usuarios/Clientes</h2></div>
                    <div class="card-body">
                        {!! Form::open(['method'=>'POST',  'files'=> true, 'route' => 'users.store']) !!}
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    {!! Form::label('Nombre') !!}
                                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group col-md-12">
                                    {!! Form::label('Email') !!}
                                    {!! Form::text('email', null, ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group col-md-12">
                                    {!! Form::label('Password') !!}
                                    {!! Form::password('password', ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group  col-md-12">
                                    {!! Form::label('Nivel de permiso') !!}
                                    {!! Form::select('permissions', ['Superadmin'=>'Superadmin','Admin'=>'Admin', 'Cliente' => 'Cliente'], null, ['placeholder' => 'Selecciona el nivel de permiso', 'class' => 'form-control']) !!}
                                </div>
                                {!!form::submit('Crear',['class' => 'btn btn-md btn-dark'])!!}

                                {!!form::button('Cancelar',['id'=>'cancel','content'=>'Cancelar','class'=>'btn btn-default btn-md'])!!}
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        document.querySelector('#cancel').addEventListener('click', e =>{
            document.location.href = "{{ route('users.index')}}";
        })
    </script>
@stop

resources/views/admin/usuarios/edit.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card">
                    <div class="card-header"><h2>Editar Usuario/Cliente</h2></div>
                    <div class="card-body">
                        {!! Form::model($user, ['method'=>'PUT',  'files'=> true, 'route' => ['users.update', $user]]) !!}
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    {!! Form::label('Nombre') !!}
                                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group col-md-12">
                                    {!! Form::label('Email') !!}
                                    {!! Form::text('email', null, ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group col-md-12">
                                    {!! Form::label('Password') !!}
                                    {!! Form::password('password', ['class' => 'form-control']) !!}
                                </div>
                                <div class="form-group  col-md-12">
                                    {!! Form::label('Nivel de permiso') !!}
                                    {!! Form::select('permissions', ['Superadmin'=>'Superadmin','Admin'=>'Admin', 'Cliente' => 'Cliente'], null, ['placeholder' => 'Selecciona el nivel de permiso', 'class' => 'form-control']) !!}
                                </div>
                                {!!form::submit('Editar',['class' => 'btn btn-md btn-dark'])!!}

                                {!!form::button('Cancelar',['id'=>'cancel','content'=>'Cancelar','class'=>'btn btn-default btn-md'])!!}
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        document.querySelector('#cancel').addEventListener('click', e =>{
            document.location.href = "{{ route('users.index')}}";
        })
    </script>
@stop

resources/views/admin/usuarios/index.blade.php
@extends('admin.main')
@section('content')
    <div class="container-fluid pt-5">
        <div class="col-md-12">
            @if (session('status'))
                <div class="alert alert-{{session('status')}} alert-dismissible fade show" role="alert">
                    <strong>{{ session('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="card">
                <div class="card-header"><h2>Usuarios/Clientes</h2></div>
                <div class="card-body">
                    <table class="table table-bordered table-hover table-sm">
                        <thead>
                            <th>NOMBRE</th>
                            <th>EMAIL</th>
                            <th>NIVEL PERMISO</th>
                            <th>ACCION</th>
                        </thead>
                        <tbody>
                             @if($users->count() > 0)
                                @foreach ($users as $user)
                                    <tr
                                        @if (auth()->user()->email === $user->email && auth()->user()->name === $user->name)
                                            style="background-color:lightblue;"
                                        @endif
                                    >
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->permissions}}</td>
                                        <td>
                                            @if (auth()->user()->permissions == 'Admin')
                                                @if ($user->permissions !== 'Superadmin')
                                                    <a href="{{route('users.edit', $user->id)}}" class="btn btn-default btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-edit"></i></a>
                                                @endif
                                            @else
                                                <a href="{{route('users.edit', $user->id)}}" class="btn btn-default btn-sm" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-edit"></i></a>
                                                <a href="#" class="btn btn-danger btn-sm" onclick="(new actions()).deleteUser({{$user->id}})"  data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="fa fa-trash"></i></a>
                                                {!! Form::open(['route' => ['users.destroy', $user->id] , 'method' => 'DELETE', 'class' => 'd-none', 'id' => 'delete_user_'.$user->id]) !!}
                                                {!! Form::close() !!}
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan = 25 align="center">No tiene usuarios</td></tr>
                            @endif
                        </tbody>
                    </table>
                    <div class="d-flex absolute-center">
                        {{$users->links()}}
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" id="adduser"  name="adduser" class="btn btn-dark " >Agregar Usuarios</button>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
    <script>
        function actions(){
            let addBtn = document.querySelector('#adduser');

            addBtn.addEventListener('click', e =>{
                document.location.href = "{{ route('users.create')}}";
            });
            this.deleteUser = (id) => {
                confirm('¿Seguro que desea eliminar este registro?') ? document.forms['delete_user_'+ id].submit() : null;
            }
        }
        actions();
    </script>
@stop